// Generated by Wrangler by running `wrangler types -c wrangler.json --experimental-include-runtime shared-cf-types.d.ts`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface Env {
}
